# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

          server-username: PinkLemonadeWizard
          server-password: ${{ secrets.PINKLEMONADEWIZARD_OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.BBCE4E01_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.BBCE4E01_SIGNING_PASSWORD }}
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" > secring.gpg
        env:
          GPG_SIGNING_KEY: ${{ secrets.BBCE4E01_SIGNING_KEY }}
      - name: Build & Publish with Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish
        env:
          SIGNING_FILE: ${{ secrets.QODANA_TOKEN }}
        run: ./gradlew clean :spellbook:build :spellbook:publish -PossrhUsername=PinkLemonadeWizard -Psigning.keyId=BBCE4E01 -Psigning.secretKeyRingFile=secring.gpg