# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package & Publish

on: [ pull_request, push ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean build
        gradle-version: 7.5
        gradle-home-cache-cleanup: true
        cache-read-only: false

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: spellbook/build/libs/*
    
    #- name: Publish
    #  uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
    #  with:
    #    arguments: publish

    #  env:
    #    ossrhUsername: ${{ secrets.OSSRHUSERNAME }}
    #    ossrhPassword: ${{ secrets.OSSRHPASSWORD }}

